import 'fake-indexeddb/auto';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { SnapshotRefreshError, writeCachedSnapshot } from '../data/activeSnapshot.ts';
import { loadBundledSnapshot } from '../data/index.ts';
import { db } from './db.ts';
import { resetSnapshotStoreForTests, useSnapshotStore } from './snapshotStore.ts';

/**
 * Store wiring over the data-layer policy: bundled seed, cache resolution,
 * silent background refresh, manual refresh. Provider I/O is stub fetch —
 * never real network.
 */

vi.spyOn(console, 'warn').mockImplementation(() => {});
vi.spyOn(console, 'info').mockImplementation(() => {});

function rejectFetch(): void {
  vi.stubGlobal('fetch', () => Promise.reject(new Error('offline in tests')));
}

beforeEach(async () => {
  await db.gamedataCache.clear();
  resetSnapshotStoreForTests();
  rejectFetch();
});

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('snapshot store', () => {
  it('seeds synchronously from the bundled snapshot (first paint has content)', () => {
    const state = useSnapshotStore.getState();
    expect(state.source).toBe('bundled');
    expect(state.resolving).toBe(true);
    expect(state.snapshot.fetchedAt).toBe(loadBundledSnapshot().fetchedAt);
    expect(state.snapshot.characters.length).toBeGreaterThan(0);
  });

  it('ensureLoaded resolves to bundled when the cache is empty', async () => {
    await useSnapshotStore.getState().ensureLoaded();
    const state = useSnapshotStore.getState();
    expect(state.source).toBe('bundled');
    expect(state.resolving).toBe(false);
    expect(state.snapshot.fetchedAt).toBe(loadBundledSnapshot().fetchedAt);
  });

  it('ensureLoaded swaps in a usable cache', async () => {
    const cachedAt = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
    await writeCachedSnapshot({ ...loadBundledSnapshot(), fetchedAt: cachedAt });

    await useSnapshotStore.getState().ensureLoaded();
    const state = useSnapshotStore.getState();
    expect(state.source).toBe('cache');
    expect(state.resolving).toBe(false);
    expect(state.snapshot.fetchedAt).toBe(cachedAt);
  });

  it('stale data keeps serving while the background refresh fails silently', async () => {
    const seen: string[] = [];
    vi.stubGlobal('fetch', (url: string) => {
      seen.push(String(url));
      return Promise.reject(new Error('offline in tests'));
    });
    // Deterministically stale cache (never the bundled file's own date —
    // that file is regenerated by an unrelated workflow).
    const staleAt = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    await writeCachedSnapshot({ ...loadBundledSnapshot(), fetchedAt: staleAt });

    await useSnapshotStore.getState().ensureLoaded();
    await vi.waitFor(() => expect(seen.length).toBeGreaterThan(0));
    const state = useSnapshotStore.getState();
    expect(state.source).toBe('cache');
    expect(state.snapshot.fetchedAt).toBe(staleAt);
    expect(state.lastCheckedAt).toBeNull();
    expect(seen[0]).toContain('encore.moe');
  });

  it('manual refresh rejects as unavailable offline and keeps serving bundled', async () => {
    const failure = await useSnapshotStore.getState().refresh().then(
      () => null,
      (err: unknown) => err,
    );
    expect(failure).toBeInstanceOf(SnapshotRefreshError);
    expect((failure as SnapshotRefreshError).kind).toBe('unavailable');
    const state = useSnapshotStore.getState();
    expect(state.refreshing).toBe(false);
    expect(state.source).toBe('bundled');
    expect(state.snapshot.fetchedAt).toBe(loadBundledSnapshot().fetchedAt);
  });

  it('manual refresh adopts, persists, and serves a newer provider snapshot', async () => {
    // Seed a deterministically stale active snapshot so the candidate the
    // pipeline stamps "now" is strictly newer on any clock.
    const staleAt = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    await writeCachedSnapshot({ ...loadBundledSnapshot(), fetchedAt: staleAt });
    const motionValues = Array.from({ length: 10 }, (_, i) => `${10 + i}%`);
    const responses = new Map<string, unknown>([
      ['/character', { roleList: [{ Id: 1, Name: 'Testina' }] }],
      [
        '/character/1',
        {
          Id: 1,
          Name: { Content: 'Testina' },
          QualityId: 5,
          ElementName: 'Aero',
          WeaponTypeName: 'Sword',
          Properties: [
            { Name: 'HP', GrowthValues: [{ level: 1, value: 800 }] },
            { Name: 'ATK', GrowthValues: [{ level: 1, value: 20 }] },
            { Name: 'DEF', GrowthValues: [{ level: 1, value: 90 }] },
          ],
          Skills: [
            {
              SkillId: 1001,
              SkillType: 'Normal Attack',
              SkillName: 'Test Strike',
              SkillDescribe: 'Deals damage.',
              SkillAttributes: [{ attributeName: 'Stage 1 DMG', values: motionValues }],
              DamageList: [{ PropertyName: 'ATK', Type: 'Basic Attack', RateLv: motionValues }],
            },
          ],
          SkillTree: [],
          ResonantChain: [1, 2, 3, 4, 5, 6].map((rank) => ({
            GroupIndex: rank,
            NodeName: `Test Chain ${rank}`,
            AttributesDescription: 'Effect text.',
          })),
        },
      ],
      ['/weapon', { weapons: [{ Id: 7, Name: 'Test Blade' }] }],
      [
        '/weapon/7',
        {
          WeaponName: 'Test Blade',
          WeaponTypeName: 'Sword',
          QualityId: 5,
          Properties: [{ Name: 'ATK', GrowthValues: [{ level: 1, value: 30 }] }],
          ResonName: 'Test Passive',
          Desc: 'Does things.',
          DescParams: [{ ArrayString: ['1'] }],
        },
      ],
      [
        '/echo',
        {
          Echo: [
            {
              Id: 42,
              Name: 'Testecho',
              FetterGroups: [
                { Id: 9, Name: 'Test Sonata', Fetters: [{ Key: 2, Name: 'x', EffectDescription: 'Aero DMG + 10%' }] },
              ],
            },
          ],
        },
      ],
      [
        '/echo/42',
        {
          Element: { Name: 'Aero' },
          FetterGroup: [9],
          Handbook: { Intensity: 'Common Class', Descrtption1: 'pool text (not parsed)' },
        },
      ],
    ]);
    vi.stubGlobal(
      'fetch',
      ((url: string) => {
        const path = String(url).replace('https://api-v2.encore.moe/api/en', '');
        const body = responses.get(path);
        if (body === undefined) return Promise.reject(new Error(`no stub for ${path}`));
        return Promise.resolve({ ok: true, json: () => Promise.resolve(body) });
      }) as unknown as typeof fetch,
    );

    const outcome = await useSnapshotStore.getState().refresh();
    expect(outcome.status).toBe('updated');
    const state = useSnapshotStore.getState();
    expect(state.source).toBe('cache');
    expect(state.refreshing).toBe(false);
    expect(state.snapshot.characters.map((c) => c.name)).toEqual(['Testina']);
    expect(state.lastCheckedAt).not.toBeNull();
    // Persisted: the cached row matches the served snapshot and is
    // strictly newer than the stale seed (the pipeline stamps fetch time).
    const row = await db.gamedataCache.get('active');
    expect(row?.fetchedAt).toBe(state.snapshot.fetchedAt);
    expect((row?.fetchedAt ?? '') > staleAt).toBe(true);
  });
});
